config/routes.rb
Rails.application.routes.draw do
  root to: "profiles#index"

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :profiles, only: [:index]

  resources :users, only: :none, shallow: true do
    resource :profile, :employers
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user

  do_not_validate_attachment_file_type :avatar

  has_attached_file :avatar, :styles => { :medium => "300x300>", :small  => "200x200>", :thumb => "100x100>"}

  def avatar_stored?
    self.avatar ? true : false
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController


  def index
  	@user = current_user if current_user
    @profiles = Profile.all
  end

  def new
  	@user = current_user if current_user
  	@profile = Profile.new
  end

  def create
    @profile = Profile.new(user_id: current_user.id,
                            first_name: profile_params[:first_name],
                            last_name: profile_params[:last_name],
                            cohort: profile_params[:cohort],
                            dob: profile_params[:dob],
                            city: profile_params[:city],
                            country: profile_params[:country],
                            personal_statement: profile_params[:personal_statement],
                            employment_status: profile_params[:employment_status],
                            startup_status: profile_params[:startup_status],
                            avatar: profile_params[:avatar])
    if @profile.save
      flash[:notice] = "Profile created successfully"
      redirect_to profiles_path
    else
      render 'new'
    end
  end

  def show
  	@user_id = params[:user_id]
    @user = User.find(@user_id)
    @profile = Profile.find_by(user_id: @user_id)
    @current_employer = @user.employers.first()
  end

 	def edit
 		@user = current_user if current_user
 		@profile = Profile.find_by(user_id: @user.id)
 	end

  def update
    @user = current_user if current_user
    @profile = Profile.find_by(user_id: @user.id)
    if @profile.update(profile_params)
      flash[:notice] = "Profile updated successfully"
      render 'show'
    else
      flash[:notice] = "Profile could not be updated"
      render 'edit'
    end
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name,
                                    :cohort, :avatar, :dob, :city,
                                    :country, :personal_statement,
                                    :employment_status, :startup_status
                                    )
  end

end

app/views/profiles/edit.html.erb
<div class="container">
  <div class="col-md-6">
  <h4>Edit your profile and save</h4>
    <div class="form-group">

<%= form_for([@user, @profile], url: user_profile_path(@user.id)) do |f| %>
<%= f.text_field :first_name, placeholder: "First Name", class: 'form-control' %>
<br>
<%= f.text_field :last_name, placeholder: "Last Name", class: 'form-control' %>
<br>
<%= f.text_field :cohort, placeholder: "Cohort", class: 'form-control' %>
<br>
<%= image_tag @profile.avatar.url(:thumb) if @profile.avatar_stored? %>
<br>
<%= f.file_field :avatar %>
<br>
<%= f.date_field :dob, class: 'form-control' %>
<br>
<%= f.text_field :city, placeholder: "City", class: 'form-control' %>
<br>
<%= f.text_field :country, placeholder: "Country", class: 'form-control' %>
<br>
<%= f.text_area :personal_statement, placeholder: "Peronal Statement", class: 'form-control height-150' %>
<br>
<%= f.submit "Update profile", class: 'form-control btn btn-info btn-fill' %>
<% end %>

</div>
</div>
</div>

app/views/profiles/index.html.erb
<div class="container">
<% if @profiles %>
  <% @profiles.each do |profile| %>

<div class="col xs-12 col-md-6">
<%= link_to user_profile_path(profile.user) do %>
<div class="card card-horizontal max-height-150">
    <div class="row">
        <div class="col-md-4 col-sm-4 col-xs-4">
            <div class="max-150-width no-overflow">
                      <%= image_tag profile.avatar.url(:small), {class: 'min-150'} if profile.avatar.url %>
        
                <div class="filter filter-azure">
                    <button type="button" class="btn btn-neutral btn-round">
                        <i class="fa fa-user"></i> View
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-8">
             <div class="content">
               <p class="category text-info">
                  <%= profile.cohort %>
                </p>

                <a class="card-link" href="#">
                    <h4 class="title"><%= profile.first_name %> <%= profile.last_name %></h4>
                </a>
                  <a class="card-link" href="#">
                <% if profile.user.employers.any? %>
                  <p class="description"><%= profile.user.employers.last.role %> @ <span><%= profile.user.employers.last.company_name %></span></p>
                <% else %>
                  <p class="description">No employment history</p>
                <% end %>
                  </a>

                 <div class="footer">
                    <div class="stats">
                        <a class="card-link" href="#">
                           <i class="fa fa-male"></i> Github
                        </a>
                    </div>

                    <div class="stats">
                        <a class="card-link" href="#">
                           <i class="fa fa-male"></i> Portfolio
                        </a>
                    </div>

                    <div class="stats">
                      <a class="card-link" href="#">
                        <i class="fa fa-comments"></i> Linkedin
                      </a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div> <!-- end card -->
          
</div> <!-- col-6-md -->
<% end %>
  <% end %>

<% else %>
    <p>No profiles here.</p>
<% end %>

app/views/profiles/new.html.erb
<div class="container">
  <div class="col-md-6">
  <h4>Fill out your profile</h4>
    <div class="form-group">

<%= form_for([@user, @profile], url: user_profile_path(@user.id)) do |f| %>
<%= f.text_field :first_name, placeholder: "First Name", class: 'form-control' %>
<br>
<%= f.text_field :last_name, placeholder: "Last Name", class: 'form-control' %>
<br>
<%= f.text_field :cohort, placeholder: "Cohort", class: 'form-control' %>
<br>
<%= f.file_field :avatar, class: 'form-control' %>
<br>
<%= f.label "Date of Birth" %>
<%= f.date_field :dob, placeholder: "DOB", class: 'form-control' %>
<br>
<%= f.text_field :city, placeholder: "City", class: 'form-control' %>
<br>
<%= f.text_field :country, placeholder: "Country", class: 'form-control' %>
<br>
<%= f.text_area :personal_statement, placeholder: "Peronal Statement", class: 'form-control' %>
<br>
<%= f.submit "Save profile", class: 'form-control btn btn-info btn-fill' %>
<% end %>

</div>
</div>
</div>

app/views/profiles/show.html.erb
<div class="container">
<div class="row">
<div class="col-xs-12 col-md-push-1">
<% if (@profile.user == current_user ) %>
<%= link_to "Edit profile", edit_user_profile_path(@user.id), {class: 'btn btn-info margin-left'} %>
<% end %>
</div>
</div>

<br>

    <div class="col-md-1"> </div>

    <div class="col xs-12 col-md-10">
    <div class="card card-horizontal main_profile">
        <div class="row profile_top">
            <div class="col-md-3 col-sm-4 col-xs-4">
                <div class="max-150-width no-overflow">
                    <!-- <img src="assets/img/ben.png" alt="..."/> -->
                    
                    <%= image_tag @profile.avatar.url(:medium), {class: 'img-responsive min-150'}  if @profile.avatar.url %>                                
                  
                </div>
            </div>
            <div class="col-md-8">
                 <div class="content">
                   <p class="category text-info">
                      <%= @profile.cohort %> 
                    </p>

                    <a class="card-link" href="#">
                        <h4 class="title"><%= @profile.first_name %> <%= @profile.last_name %></h4>
                    </a>


                    <% if @profile.user.employers.any? %>
                    <a class="card-link" href="#">
                  <p class="description"><%= @profile.user.employers.last.role %> @ <span><%= @profile.user.employers.last.company_name %></span></p>
                <% else %>
                  <p class="description">No employment history</p>
                <% end %>

                     <div class="footer">
                        <div class="stats">
                            <a class="card-link" href="#">
                               <i class="fa fa-male"></i> Github
                            </a>
                        </div>

                        <div class="stats">
                            <a class="card-link" href="#">
                               <i class="fa fa-male"></i> Portfolio
                            </a>
                        </div>
                  
                        <div class="stats">
                          <a class="card-link" href="#">
                            <i class="fa fa-comments"></i> Linkedin
                          </a>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
          <div class="col-xs-1"> </div>
          <div class="col-xs-10 languages">
            <h4>My Languages</h4>
            <p>Ruby, JavaScript etc.</p>
          </div>
          <div class="col-xs-1"> </div>
        </div>

        <div class="row">
          <div class="col-xs-1"> </div>
          <div class="col-xs-10 personal_statement">

          <div class="row">
            <div class="col-xs-6"><h4>About Me</h4></div>
            <div class="col-xs-6"><h4 class="profile_location"><%= @profile.city %>, <%= @profile.country %></h4></div>
          </div>
            <p><%= @profile.personal_statement %></p>
          </div>
          <div class="col-xs-1"> </div>
        </div>


    </div> <!-- end card -->


  </div> <!-- col-6-md -->

   <div class="col-md-1"> </div>

</div> <!-- container -->